/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package formularioGestion;

import javax.swing.JOptionPane;

/**
 *
 * @author juanj
 */
public class mainApp extends javax.swing.JFrame {

    /**
     * Creates new form mainApp
     */
    public mainApp() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        codTexto = new javax.swing.JLabel();
        nombreTexto = new javax.swing.JLabel();
        cantidadTexto = new javax.swing.JLabel();
        DescripcionTexto = new javax.swing.JLabel();
        txtNombre = new javax.swing.JTextField();
        txtCodigo = new javax.swing.JTextField();
        botonInsertar = new javax.swing.JButton();
        botonBuscar = new javax.swing.JButton();
        botonSalir = new javax.swing.JButton();
        botonMostrar = new javax.swing.JButton();
        listadoTexto = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        txtCantidad = new javax.swing.JTextField();
        txtDescripcion = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtListadoProd = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Gestión de Productos");
        setResizable(false);

        codTexto.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        codTexto.setText("Código");

        nombreTexto.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        nombreTexto.setText("Nombre");

        cantidadTexto.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        cantidadTexto.setText("Cantidad");

        DescripcionTexto.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        DescripcionTexto.setText("Descripción");

        botonInsertar.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        botonInsertar.setText("Insertar");
        botonInsertar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonInsertarActionPerformed(evt);
            }
        });

        botonBuscar.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        botonBuscar.setText("Buscar");
        botonBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonBuscarActionPerformed(evt);
            }
        });

        botonSalir.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        botonSalir.setText("Salir");
        botonSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonSalirActionPerformed(evt);
            }
        });

        botonMostrar.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        botonMostrar.setText("Mostrar");
        botonMostrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonMostrarActionPerformed(evt);
            }
        });

        listadoTexto.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        listadoTexto.setText("Listado de productos");

        jSeparator1.setOrientation(javax.swing.SwingConstants.VERTICAL);

        txtListadoProd.setColumns(20);
        txtListadoProd.setRows(5);
        jScrollPane1.setViewportView(txtListadoProd);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(codTexto, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(nombreTexto, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(cantidadTexto, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(DescripcionTexto, javax.swing.GroupLayout.Alignment.TRAILING))
                                .addGap(22, 22, 22)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(txtCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(txtCantidad, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtDescripcion, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(botonBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(botonInsertar, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(24, 24, 24)
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 13, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(listadoTexto)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 307, Short.MAX_VALUE))
                            .addComponent(jScrollPane1)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(287, 287, 287)
                        .addComponent(botonMostrar, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(botonSalir, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(19, 19, 19))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(13, 13, 13)
                        .addComponent(listadoTexto)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap(37, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(codTexto))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(nombreTexto))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtCantidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cantidadTexto))
                        .addGap(12, 12, 12)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtDescripcion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(DescripcionTexto))))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(botonInsertar, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botonBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botonMostrar, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botonSalir, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(19, Short.MAX_VALUE))
            .addComponent(jSeparator1)
        );

        setSize(new java.awt.Dimension(778, 285));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void botonSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonSalirActionPerformed
        /*Con esto al pulsar el botón "salir" se abre una ventana que nos avisa de que el programa se va a cerrar, y nos deja elegir entre "si o no".*/
        String [] opciones = {"Si", "No"};
        int opcionNum = JOptionPane.showOptionDialog(this, "El programa se va a cerrar ¿Quieres continuar?.", "El programa se va a cerrar", JOptionPane.YES_NO_CANCEL_OPTION, JOptionPane.INFORMATION_MESSAGE, null, opciones, opciones[0]);  
        
        if(opcionNum==0){
            System.exit(0);   
        } 
        
        else{
            
        }
        
        
    }//GEN-LAST:event_botonSalirActionPerformed

    private void botonInsertarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonInsertarActionPerformed
        //Declaramos nuestra clase
        gestionDatos insertaDatos = new gestionDatos();
        
        //Y usando nuestro método estático validamos si tanto código como cantidad son númericos.
        gestionDatos.validadorNumerico(txtCodigo.getText(), txtCantidad.getText());
        //Enviamos nuestro código para verificar que no exista ya dentro de nuestro archivo.
        insertaDatos.comprobadorCodigos(txtCodigo.getText());
        //Opciones que utilizará nuestro JOption Pane.
        String[] opciones = {"De Acuerdo"}; 
        /*Aprovechamos estos datos para hacer un "if" el cual en caso de que sean númericos y
        de que no sea un número ya existente, se recogerán y se guardarán en nuestro archivo*/ 
        if(gestionDatos.isCodigoNumerico()==true && gestionDatos.isCantidadNumerico()==true && insertaDatos.isCodRepetido()==false){
            //Método al cuál enviamos nuestros datos para que los procese y los guarde en el archivo.
            insertaDatos.insertaDatos(Integer.parseInt(txtCodigo.getText()), txtNombre.getText(), Integer.parseInt(txtCantidad.getText()), txtDescripcion.getText());
                        
            // Después de añadirlos, se limpiará lo escrito.
            txtCodigo.setText("");
            txtNombre.setText("");
            txtCantidad.setText("");
            txtDescripcion.setText("");
            //Y nos mostrará un mensaje comentándonos que nuestro producto ha sido guardado.
            JOptionPane.showOptionDialog(this, "El producto ha sido añadido correctamente.", "Producto Añadido", JOptionPane.YES_NO_CANCEL_OPTION, JOptionPane.INFORMATION_MESSAGE, null, opciones, opciones[0]);  

        }
        //En el caso contrario, si los datos introducidos son erroneos, nos devolverá un mensaje concreto para poder corregirlo.
        else{
            

            if (gestionDatos.isCodigoNumerico()==false && gestionDatos.isCantidadNumerico()==false) {
            JOptionPane.showOptionDialog(this, "El Código y la Cantidad introducida son erroneos, vuelve a intentarlo.", "Datos Erroneos", JOptionPane.YES_NO_CANCEL_OPTION, JOptionPane.WARNING_MESSAGE, null, opciones, opciones[0]);  
  
            }
            
            else if (gestionDatos.isCodigoNumerico()==false && gestionDatos.isCantidadNumerico()==true ){
                JOptionPane.showOptionDialog(this, "El Código introducido es erroneo, vuelve a intentarlo.", "Datos Erroneos", JOptionPane.YES_NO_CANCEL_OPTION, JOptionPane.WARNING_MESSAGE, null, opciones, opciones[0]);  

            }
            else if(insertaDatos.isCodRepetido() == true && gestionDatos.isCantidadNumerico()==false){
                JOptionPane.showOptionDialog(this, "El código ya existe y la cantidad es Erronea.", "Datos Erroneos", JOptionPane.YES_NO_CANCEL_OPTION, JOptionPane.WARNING_MESSAGE, null, opciones, opciones[0]);  

            }
            
            else if(insertaDatos.isCodRepetido() == true && gestionDatos.isCantidadNumerico()==true){
                JOptionPane.showOptionDialog(this, "El código ya existe, prueba otro.", "Código ya Existente", JOptionPane.YES_NO_CANCEL_OPTION, JOptionPane.WARNING_MESSAGE, null, opciones, opciones[0]);  

            }
            else{
                JOptionPane.showOptionDialog(this, "La Cantidad introducida es erronea, vuelve a intentarlo.", "Datos Erroneos", JOptionPane.YES_NO_CANCEL_OPTION, JOptionPane.WARNING_MESSAGE, null, opciones, opciones[0]);  

            }
            
            
        }
        
       
    }//GEN-LAST:event_botonInsertarActionPerformed

    private void botonMostrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonMostrarActionPerformed
         //Llamamos a nuestro método "muestraDatos" para recuperar los datos del archivo.
         gestionDatos mostrar = new gestionDatos();
         
         mostrar.muestraDatos();
         //Se lo añadimos a nuestra JTextArea usando un getter del atributo string con el texto formateado.
         txtListadoProd.setText(mostrar.getProdAlmacenados());
        
    }//GEN-LAST:event_botonMostrarActionPerformed

    private void botonBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonBuscarActionPerformed
        gestionDatos buscar = new gestionDatos();
        /*Recogemos el código que queremos buscar, tecleado en nuestro programa y lo enviamos
        a nuestro método*/
        buscar.buscaProducto(txtCodigo.getText());
        
        //Además útilizamos nuestro método estático para probar si código es númerico.
        gestionDatos.validadorNumerico(txtCodigo.getText(), txtCantidad.getText());
        
        /*Aprovechando ambos datos, de si mi código es númerico, y si mi busqueda en el archivo ha sido encontrada
        hago un if, el cual si ambas cosas son "true" lo añadirá los datos buscados en sus respetivos "jLabels".*/
        if(gestionDatos.isCodigoNumerico()==true && buscar.isBusquedaEncontrada() == true ){
            String[] opciones = {"Ok"}; 
           

            
            txtCodigo.setText(Integer.toString(buscar.getCodigo()));
            txtNombre.setText(buscar.getNombre());
            txtCantidad.setText(Integer.toString(buscar.getCantidad()));
            txtDescripcion.setText(buscar.getDescripcion());
            
            JOptionPane.showOptionDialog(this, "Busqueda realizada con éxito", "Producto Encontrado", JOptionPane.YES_NO_CANCEL_OPTION, JOptionPane.INFORMATION_MESSAGE, null, opciones, opciones[0]);

            
            
        }
        /*En el caso contrario, si hay algún tipo de error, se mostrarán mensajes 
        de error concretos con el error en cuestión*/
        else{
            String[] opciones = {"De Acuerdo"}; 

            if (buscar.isBusquedaEncontrada() == false && gestionDatos.isCodigoNumerico()==true ) {
                JOptionPane.showOptionDialog(this, "El producto no existe, vuelve a intentarlo.", "Producto no Encontrado", JOptionPane.YES_NO_CANCEL_OPTION, JOptionPane.WARNING_MESSAGE, null, opciones, opciones[0]);
  
            }
            
            else {
                JOptionPane.showOptionDialog(this, "El Código introducido debe ser númerico, vuelve a intentarlo.", "Datos Erroneos", JOptionPane.YES_NO_CANCEL_OPTION, JOptionPane.WARNING_MESSAGE, null, opciones, opciones[0]);  

            }
            
            
            
        }
        
        
        
    }//GEN-LAST:event_botonBuscarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(mainApp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(mainApp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(mainApp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(mainApp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new mainApp().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel DescripcionTexto;
    private javax.swing.JButton botonBuscar;
    private javax.swing.JButton botonInsertar;
    private javax.swing.JButton botonMostrar;
    private javax.swing.JButton botonSalir;
    private javax.swing.JLabel cantidadTexto;
    private javax.swing.JLabel codTexto;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel listadoTexto;
    private javax.swing.JLabel nombreTexto;
    private javax.swing.JTextField txtCantidad;
    private javax.swing.JTextField txtCodigo;
    private javax.swing.JTextField txtDescripcion;
    private javax.swing.JTextArea txtListadoProd;
    private javax.swing.JTextField txtNombre;
    // End of variables declaration//GEN-END:variables
}
